In [15]:
import cv2
import numpy as np

In [16]:
input = cv2.imread(r'C:\Users\hp\opencv_project\image_examples\elephant.jpg')

In [17]:
print(input)

[[[255 255 241]
  [254 254 240]
  [254 254 240]
  ...
  [255 255 241]
  [255 255 241]
  [255 255 241]]

 [[255 255 241]
  [254 254 240]
  [254 254 240]
  ...
  [255 255 241]
  [255 255 241]
  [255 255 241]]

 [[255 255 241]
  [255 254 240]
  [254 254 240]
  ...
  [255 255 241]
  [255 255 241]
  [255 255 241]]

 ...

 [[121 159 183]
  [141 171 196]
  [169 191 219]
  ...
  [  0   7  22]
  [  0   7  22]
  [  1   8  25]]

 [[143 183 208]
  [147 177 204]
  [168 190 218]
  ...
  [  2   9  24]
  [  0   6  23]
  [  0   7  24]]

 [[133 173 198]
  [125 158 184]
  [143 167 195]
  ...
  [  2  10  27]
  [  0   8  25]
  [  0   8  25]]]


In [18]:
cv2.imshow('The Elephant Image', input)

cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
print(input.shape)

(519, 778, 3)


In [13]:
print('Height: ',input.shape[0], 'pixels')
print('Height: ',input.shape[1], 'pixels')

Height:  519 pixels
Height:  778 pixels


In [14]:
cv2.imwrite('output.jpg',input)

True